#!/usr/bin/env python3
import rospy

def main():
    global_file = rospy.get_param("~global_file")
    per_robot_file = rospy.get_param("~per_robot_file")
    robots = rospy.get_param("~robots")
    output_file = rospy.get_param("~output_file")

    with open(global_file) as f:
        out_string = f.read()

    with open(per_robot_file) as f:
        per_robot_string = f.read()

    for name in robots:
        if name == "none":
            continue
        out_string += str(per_robot_string).replace("$(arg robot)", name)
    with open(output_file, "w+") as f:
        f.write(out_string)


if __name__ == "__main__":
    rospy.init_node("multirobot_generator")
    main()
